// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2MEl0fstEPyLZMpDUeBi6MP5MPUgQdE',
    appId: '1:547966749439:web:4f2fb76102a25e2143daca',
    messagingSenderId: '547966749439',
    projectId: 'vrchat-pictures',
    authDomain: 'vrchat-pictures.firebaseapp.com',
    storageBucket: 'vrchat-pictures.appspot.com',
    measurementId: 'G-251D3N9BFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARyGlyrhsskDfiZclBYlTEFU_2IBkliJQ',
    appId: '1:547966749439:android:a6d4b58a0bef9c3743daca',
    messagingSenderId: '547966749439',
    projectId: 'vrchat-pictures',
    storageBucket: 'vrchat-pictures.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjB08SSvJwowjMzH_W5zfpBkq_BqWd2ks',
    appId: '1:547966749439:ios:ad50ff025441b9ab43daca',
    messagingSenderId: '547966749439',
    projectId: 'vrchat-pictures',
    storageBucket: 'vrchat-pictures.appspot.com',
    iosBundleId: 'com.example.vrchatPicturesWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjB08SSvJwowjMzH_W5zfpBkq_BqWd2ks',
    appId: '1:547966749439:ios:ad50ff025441b9ab43daca',
    messagingSenderId: '547966749439',
    projectId: 'vrchat-pictures',
    storageBucket: 'vrchat-pictures.appspot.com',
    iosBundleId: 'com.example.vrchatPicturesWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm2MEl0fstEPyLZMpDUeBi6MP5MPUgQdE',
    appId: '1:547966749439:web:f5c788d50517b52643daca',
    messagingSenderId: '547966749439',
    projectId: 'vrchat-pictures',
    authDomain: 'vrchat-pictures.firebaseapp.com',
    storageBucket: 'vrchat-pictures.appspot.com',
    measurementId: 'G-Y6D2E2HMXE',
  );
}
